language: python
python:
  - "3.6"
env:
  - REACT_APP_USERS_SERVICE_URL = http://127.0.0.1
services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose -f docker-compose-prod.yml run users sh -c "python manage.py test && flake8 project"