FROM python:3.6.4

# Dependencies
RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends netcat \
    && apt-get -q clean

# set working directory 
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add app
COPY . /usr/src/app

# runserver
CMD ["./entrypoint.sh"]